# Generated by Django 5.0 on 2024-03-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockprice',
            name='adj_close_price',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='low_price',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='volume',
        ),
    ]
