# Generated by Django 5.0 on 2024-04-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_stock', '0003_alter_stock_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_stock_data_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
