version: '3'

services:
  backend:
    build:
      context: ./stockpred
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn stockpred.wsgi:application --bind 0.0.0.0:8000 --timeout 300"
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./stock-predictor-frontend
    volumes:
      - react_build:/react/build
    # command: npm start
    # ports:
    #   - "3000:3000"
    # depends_on:
    #   - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/stock-predictor-frontend
    depends_on:
      - backend
      - frontend
  
volumes:
  react_build: